abstract: Parse and write sieve scripts
author: Yves Agostini - Univ Metz - <agostini@univ-metz.fr>
build_requires: 
  Pod::Coverage: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Net-Sieve-Script
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0.3
  perl: 5.6.0
tests: t/*.t
version: 0.05
