--- 
abstract: Parse and write sieve scripts
author: 
  - Yves Agostini - Univ Metz - <agostini@univ-metz.fr>
build_requires: 
  Pod::Coverage: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Net-Sieve-Script
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0.3
  perl: 5.6.0
tests: t/*.t
version: 0.08
